### PR TITLE
Fix showing older versions of maps

### PR DESCRIPTION
**Pull request by KCMertens**
Poe.ninja has an extra "variant" field in the price response, I've added the field to the rates objects.
Then I determine the correct variant string for maps and get the right variant from the poe.ninja prices.

If we don't set the variant for an item, it'll just fall back to the current behavior of matching on the lowercase name and links.

Determining the variant is a bit of a dirty approach currently, but I can't see any other data to base if off of in the poe stash item objects.

### CODE REVIEW

**Comment by nijikokun** [comment]
Oh sweet, I was wondering how to determine the map names, if you have older maps check out the new version, I need to coordinate old maps with ninja info and don't have any myself. https://github.com/currency-cop/currency-cop/issues/34

**Comment by KCMertens** [comment]
I've  got some old maps in std, might be missing 1 series but I can just buy some. Headed to work atm but I'll give it a try when I get back home tonight.

**Comment by KCMertens** [comment]
Just done some prodding around in the new version trying to port the code.

Determining the right variant for a map in is all of 5 lines of code, but it seems like only unique maps end up in the report for some reason. 

Where I'm stuck is what happens after we get [here](https://github.com/currency-cop/currency-cop/blob/1c0453e1cf1e8477c80f07ce20acb06302e10eab/src/classes/api.js#L233). The debugger in electron isn't playing nice with me for some reason and I keep getting booted into webpack mangled code instead of the sourcemap making it very hard to trace the data. 

Can you offer any insight where the items created there are processed further and matched with the poe.ninja prices? 

Maybe we should close this and make an issue to discuss?

**Comment by KCMertens** [comment]
After a night's sleep I got basics working in the new version. 
I noticed a couple of edge cases such as unique maps never having a variant, and beachhead maps having a T5/T10/T15 variant, so I went ahead and shot the poe.ninja guy a message to see if he can provide some insight into how item variants are determined for other items. 

If it pans out I'll get the most common cases fixed and open a new pr.

**Pull request closed without merging**
